task: MNIST

dataset: cifar10
data_root: /data
random_rotation: 10
random_crop: 5
pretensor_transform: False

device: cuda
num_workers: 2
batch_size: 64
epochs: 1000
lr: 0.01
lr_atk: 0.0001
seed: 999
save_model: False
train_epoch: 1

target_label: 1
eps: 0.3
alpha: 0.5
clsmodel: vgg11

attack_model: autoencoder
attack_portion: 1.0
mode: all2one
epochs_per_external_eval: 50
cls_test_epochs: 20
best_threshold: 0.1
verbose: 1
avoid_cls_reinit: False

test_eps: None
test_alpha: None
test_n_size: 10
